### PR TITLE
Added a setContent method in indexjs line 95

### PR DESCRIPTION
**Pull request by CDSappBuilders**
This is my first please indulgence is requested if did something wrong

### CODE REVIEW

**Review by SamVerschueren — CHANGES_REQUESTED** [review]
Hi, thanks for your PR! Let me guide you through this.

Please do not make unrelated changes. It looks like you changed indentation etc. Don't :)! If you fix that first I will review the actual changes that matter.

**Comment by CDSappBuilders** [comment]
Hi thanks for your reply,
I didn't realise that I took the index.js from the node-module installed by npm, instead of taking it from the repo. And they are really not the same. Sorry for this mistake, don't want to waste your time.
I'll take a better look next time.

**Comment by SamVerschueren** [comment]
No problem. Do you need any references on how to get started with your first pull request? We all started out like that so I'm definitely willing to push you in the right direction.

**Comment by CDSappBuilders** [comment]
Yes, I would be happy to have some docs on PRs.
But first, could you tell me why the node_module's index.js seems to be out dated (not using the setElement function wich is on the repo's index.js) should I upgrade it (seems like versions are the same)?

**Comment by SamVerschueren** [comment]
As you can see in the [commit history](https://github.com/SamVerschueren/cordova-config/commits/master), I did some new changes since the last release to npm. This means that the code on npm is older then the one here. You should always start from the code on GitHub because you can't know if someone else did some tweaks or improvements since the last release.

Maybe http://makeapullrequest.com/ could help you with how to make a PR. But because you already got this far, maybe most of it is irrelevant. 
I'd suggest to checkout the `master` branch again and create a new branch. Work from what's already in there. Add the method you want and ideally write some tests. Make the PR and I will review it.

If you have any questions, don't hesitate to ask.

**Comment by CDSappBuilders** [comment]
Thanks very much for your welcome.

First lesson learned and thanks again for this one,

i'll do as you say regarding your project

we keep in touch, by

2017-01-16 9:39 GMT+01:00 Sam Verschueren <notifications@github.com>:

**Comment by SamVerschueren** [comment]
ping @CDSappBuilders

**Comment by SamVerschueren** [comment]
Closing this one for now. Feel free to ping me back to reopen once you processed my feedback.

**Comment by CDSappBuilders** [comment]
Hi,
Sorry I didn't react to your ping for I don't really know what pings are in
github.

You are right about closing this PR because it wasn't relevant since i
didn't have an up-to-date version, with the setElement function witch is
pretty helpfull and  make my "improvement" a bit useless.

Anyway, thanks for everything,
By

2017-02-27 21:06 GMT+01:00 Sam Verschueren <notifications@github.com>:

**Comment by SamVerschueren** [comment]
No problem. I just added a `ping` message so you will get a notification (email, github) that something new was said in this topic because you might have forgotten about it. It happens me a lot as well :). No problem! Kind regards.

**Comment by CDSappBuilders** [comment]
Hi Sam,

Since you welcomed me so well, I thought you had to be the first to know
what I did with your work (cordova-config):

https://github.com/CDSappBuilders/The-Cordovizer

I'll be glad you let me know what you think about it.

Thanks By

2017-03-01 12:10 GMT+01:00 Sam Verschueren <notifications@github.com>:

**Comment by SamVerschueren** [comment]
Cool. If you happen to have a macOS build, let me know.

**Comment by CDSappBuilders** [comment]
Yep, that's next step...

**Comment by CDSappBuilders** [comment]
Nothing to see, but I append to notice you're from Bruges, means we are regionnaly close, I'm in North-France. Is Bruges french-speaking or nederlanden-speaking?

**Comment by SamVerschueren** [comment]
Dutch speaking :)

**Pull request closed without merging**
